# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Beringungsoberflaeche\BearbeitungVerwerfen\BearbVerwerfen\widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Widget(object):
    def setupUi(self, Widget):
        Widget.setObjectName("Widget")
        Widget.resize(302, 82)
        self.formLayoutWidget_2 = QtWidgets.QWidget(Widget)
        self.formLayoutWidget_2.setGeometry(QtCore.QRect(10, 10, 281, 61))
        self.formLayoutWidget_2.setObjectName("formLayoutWidget_2")
        self.FRM_verwerfen = QtWidgets.QFormLayout(self.formLayoutWidget_2)
        self.FRM_verwerfen.setContentsMargins(0, 0, 0, 0)
        self.FRM_verwerfen.setObjectName("FRM_verwerfen")
        self.label_17 = QtWidgets.QLabel(self.formLayoutWidget_2)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.FRM_verwerfen.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.label_17)
        self.BTN_YN = QtWidgets.QDialogButtonBox(self.formLayoutWidget_2)
        self.BTN_YN.setOrientation(QtCore.Qt.Horizontal)
        self.BTN_YN.setStandardButtons(QtWidgets.QDialogButtonBox.No|QtWidgets.QDialogButtonBox.Yes)
        self.BTN_YN.setCenterButtons(True)
        self.BTN_YN.setObjectName("BTN_YN")
        self.FRM_verwerfen.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.BTN_YN)

        self.retranslateUi(Widget)
        QtCore.QMetaObject.connectSlotsByName(Widget)

    def retranslateUi(self, Widget):
        _translate = QtCore.QCoreApplication.translate
        Widget.setWindowTitle(_translate("Widget", "Widget"))
        self.label_17.setText(_translate("Widget", "Bearbeitung wirklich verwerfen?"))
