# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Beringungsoberflaeche\dialog_new_user.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QLineEdit



class Ui_Dialogs(QtWidgets.QDialog):
    def __init__(self, level=None):
        super().__init__(parent=None)
        if not level or type(level) != list:
            self.level = ['1']
        else:
            level.sort()
            self.level = [str(element) for element in level]

    def setupUi(self):
        self.resize(430, 177)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self)
        self.verticalLayout_3.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.label = QtWidgets.QLabel(self)
        self.label.setObjectName("label")
        self.verticalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.INP_username = QtWidgets.QLineEdit(self)
        self.INP_username.setObjectName("INP_username")
        self.verticalLayout_2.addWidget(self.INP_username)
        self.INP_pw = QtWidgets.QLineEdit(self)
        self.INP_pw.setText("")
        self.INP_pw.setObjectName("INP_pw")
        self.verticalLayout_2.addWidget(self.INP_pw)
        self.INP_pw_wdh = QtWidgets.QLineEdit(self)
        self.INP_pw_wdh.setText("")
        self.INP_pw_wdh.setObjectName("INP_pw_wdh")
        self.verticalLayout_2.addWidget(self.INP_pw_wdh)
        self.CMB_lvl = QtWidgets.QComboBox(self)
        self.CMB_lvl.setObjectName("CMB_lvl")
        self.verticalLayout_2.addWidget(self.CMB_lvl)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.BTN_save = QtWidgets.QPushButton(self)
        self.BTN_save.setObjectName("BTN_save")
        self.horizontalLayout_2.addWidget(self.BTN_save)
        self.BTN_cancel = QtWidgets.QPushButton(self)
        self.BTN_cancel.setObjectName("BTN_cancel")
        self.horizontalLayout_2.addWidget(self.BTN_cancel)
        self.verticalLayout_3.addLayout(self.horizontalLayout_2)

        self.level.sort()
        level_set = set(self.level)
        level_list = list(level_set)
        self.CMB_lvl.addItems(level_list)

        self.INP_pw.setEchoMode(QLineEdit.Password)
        self.INP_pw_wdh.setEchoMode(QLineEdit.Password)
        self.setWindowTitle("Benutzerverwaltung: neuer Benutzer")
        self.label.setText("Benutzername*")
        self.label_2.setText("Passwort*")
        self.label_3.setText("Passwort Wiederholung*")
        self.label_4.setText("Benutzerlevel*")
        self.INP_username.setPlaceholderText("Name ...")
        self.BTN_save.setText("Speichern")
        self.BTN_cancel.setText("Abbrechen")

        self.BTN_save.clicked.connect(self.save)
        self.BTN_cancel.clicked.connect(self.reject)

        QtCore.QMetaObject.connectSlotsByName(self)

    def save(self):
        u = self.INP_username.text()
        pw = self.INP_pw.text()
        pw2 = self.INP_pw_wdh.text()
        lvl = self.CMB_lvl.currentText()
        fehlertext = ""
        err = 0

        if len(u) <= 0:
            fehlertext += "Username fehlt!\n"
            err = 1
        if len(pw) <= 0:
            fehlertext += "Passwort fehlt!\n"
            err = 1
        """if u == pw:
            fehlertext += "Username und Passwort dürfen nicht identisch sein.\n"
            err = 1"""
        if len(pw2) <= 0:
            fehlertext += "Passwortwiederholung fehlt!\n"
            err = 1
        if pw != pw2:
            fehlertext += "Passwörter stimmen nicht überein.\n"
            err = 1
        if len(lvl) <= 0:
            fehlertext += "Kein Benutzerlevel ausgewählt.\n"
            err = 1
        if err == 0:
            self.accept()
            self.close()
        else:
            msgb = QtWidgets.QMessageBox()
            msgb.setWindowTitle("Fehler")
            msgb.setText(fehlertext)
            msgb.exec_()

